default_stages:
- commit
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=5000]
  - id: trailing-whitespace
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: detect-private-key
  - id: mixed-line-ending
  - id: pretty-format-json
    args: [--autofix]
    exclude: \.ipynb$

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.10
  hooks:
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python, pyi ]

- repo: https://github.com/jendrikseipp/vulture
  rev: v2.6
  hooks:
    - id: vulture
