default_stages:
- commit

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=64]
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: detect-private-key
  - id: mixed-line-ending
  - id: check-json
  - id: pretty-format-json
    args: [--autofix]
    exclude: \.ipynb$
  - id: check-yaml

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.3
  hooks:
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python, pyi ]


- repo: https://github.com/jendrikseipp/vulture
  rev: v2.13
  hooks:
    - id: vulture
