[project]
name = "iokit"
version = "0.4.0"
description = "Input Output Kit"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Vladislav A. Proskurov", email = "rilshok@pm.me"},
]
dependencies = [
    "humanize>=4.9.0",
    "pytz>=2024.1",
    "typing-extensions>=4.8.0",
    "xxhash>=3.4.1",
]


[project.optional-dependencies]
all = ["iokit[image,array,audio,table,config,crypto,web]"]
dev = ["iokit[all,torch,lint,test]"]
image = ["Pillow>=10.4.0"]
array = ["numpy>=1.21.1"]
audio = ["soundfile>=0.12.1", "numpy>=1.21.1"]
table = ["pandas>=1.5.3"]
config = ["PyYAML>=6.0.1", "python-dotenv>=1.0.1", "jsonlines>=4.0.0"]
crypto = ["cryptography>=41.0.7"]
web = ["requests>=2.32.3", "python-dateutil>=2.8.2"]
torch = ["iokit[audio]", "torchaudio>=2.0.0"]
notebook = ["ipython>=8.0.0"]
lint = [
    "mypy>=1.7.1",
    "ruff>=0.6.3",
    "types-pytz>=2024.1",
    "types-requests>=2.31.0",
    "types-PyYAML>=6.0.12",
    "types-python-dateutil>=2.8.19",
]
test = [
    "pytest>=8.2.2",
    "pytest-cov==6.0.0",
    "pytest-xdist>=3.6.1",
]



[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"


[project.urls]
Homepage = "https://github.com/rilshok/iokit"
Repository = "https://github.com/rilshok/iokit.git"
Issues = "https://github.com/rilshok/iokit/issues"


[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "network: test requires internet access",
]


[tool.mypy]
strict = true


[tool.vulture]
make_whitelist = true
sort_by_size = true
verbose = false
min_confidence = 100
paths = ["src/iokit"]


[tool.ruff]
line-length = 100


[tool.ruff.format]
docstring-code-format = true


[tool.ruff.lint]
select = [
    "RUF",
    "W",
    "E",
    "F",
    "UP",
    "YTT",
    "B",
    "C4",
    "T10",
    "SIM",
    "I",
    "PGH",
    "COM",
    "RSE",
    "FLY",
    "RET",
    "TC",
    "FURB",
    "A",
    "S",
    "TRY",
    "EM",
    "ANN",
    "BLE",
    "N",
    "C90",
    "FBT",
    "SLF",
    "TID",
    "ARG",
    "PTH",
    "NPY",
    "PERF",
    "PL",
]
ignore = [
    "RUF100",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["PLR2004", "PLR0915", "S101", "S106", "ANN201", "SLF001"]
